#!/usr/bin/perl -w
print "which directory?\n"
chomp(my $dir = <STDIN>);
if ( $dir =~ /^\s+\z){
  chdir or die "can't find directory: $!";
}else{
  chdir $dir or die "can't find directory: $!";
}
open DOT, "." or die "can't open dot: $!"; #.是当前目录
foreach (sort readdir DOT){
  print "$_\n";
}
