#!/usr/bin/perl -w
use File::Spec;
use File::Basename;

my($source, $dest) = @ARGV;
if (-d $dest){
    my $basename = basename $source;
    $dest = File::Spec->catfile($dest, $basename);
}
link $source, $dest or die "can't rename:$!\n";