#!/usr/bin/perl -w
my ($year, $month, $day) = (localtime)[5,4,3];
$year += 1900; $month =+1;
sprintf '%4d-%02d-%02d', $year, $month, $day;
foreach my $file ( glob('*')){
    my ($atime, $mtime ) = (stat)[8,9];
    printf "%-20s %10d %10d\n", $file, $atime, $mtime;
}

foreach my $file ( glob('*')){
    my ($atime, $mtime ) = map {
        my ($year, $month, $day) = (localtime)[5,4,3];
        $year += 1900; $month =+1;
        sprintf '%4d-%02d-%02d', $year, $month, $day;
    } (stat $file)[8,9];
    
    printf "%-20s %10d %10d\n", $file, $atime, $mtime;
}