#!/usr/bin/perl -w
print "what's the first input number?\n";
chomp($num1 = <STDIN>);
print "what's the second input number?\n";
chomp($num2 = <STDIN>);
$result = $num1 * $num2;
print "the result is $result.\n";
