#!/usr/bin/perl -w
sub total {
    my $sum = 0; 
    foreach my $number (@_){
        $sum += $number;
    }
    $sum;
}

my @fred = qw { 1 3 5 7 9 };
my $fred_total = total(@fred);
print "the total of \@fred is $fred_total.\n";