#!/usr/bin/perl -w
greet("Fred");
greet("Barney");
state $last_person;
sub greet {
    my $name = shift;
    print "Hi, $name! ";  
    if (defined $last_person){
        print "$last_person is also here!\n";
    }else{
        print "You are the first person!\n";
    }
    $last_person = $name;
}
